---

- name: Install apt packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items:
      - git
      - ufw
      - apache2
      - libapache2-mod-wsgi
      - postgresql
      - psycopg2
      - python-pip

- include: ufw.yml

- include: project.yml

- include: apache.yml

- include: database.yml
