---

- name: Install apt packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items:
      - git
      - ufw
      - apache2
      - libapache2-mod-wsgi
      - postgresql
      - psycopg2
      - python-pip

- name: Ditch password SSH authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh

- name: Disable root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh

- include: ufw.yml

- include: project.yml

- include: apache.yml

- include: database.yml
